//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace View
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class GameView
	{
		public void ShowBoard()
		{
			throw new System.NotImplementedException();
		}

		public void ShowGameOver()
		{
			throw new System.NotImplementedException();
		}

	}
}

