//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controller
{
	using Model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using View;

	public class GameController
	{

		public virtual bool isGameOver
		{
			get;
			set;
		}

	    public Board board;
        
	    public GameView gameView;

	    public GameController()
	    {
            board = new Board();
	        gameView = new GameView(this);
	    }
	}
}

