//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Board
	{
	    public Array boardArray;
	    public LinkedList<BaseTile> tileList0;
        public LinkedList<BaseTile> tileList1;
        public LinkedList<BaseTile> tileList2;
        public LinkedList<BaseTile> tileList3;
        public LinkedList<BaseTile> tileList4;
        public LinkedList<BaseTile> tileList5;
        public LinkedList<BaseTile> tileList6;
        public LinkedList<BaseTile> tileList7;
        public LinkedList<BaseTile> tileList8;

	    public int switchTileCounter = 1;

        //TODO Array en LinkedList
        public Board()
	    {
	        boardArray = new Array[9];
            tileList0 = new LinkedList<BaseTile>();
            tileList1 = new LinkedList<BaseTile>();
            tileList2 = new LinkedList<BaseTile>();
            tileList3 = new LinkedList<BaseTile>();
            tileList4 = new LinkedList<BaseTile>();
            tileList5 = new LinkedList<BaseTile>();
            tileList6 = new LinkedList<BaseTile>();
            tileList7 = new LinkedList<BaseTile>();
            tileList8 = new LinkedList<BaseTile>();
        }
	}
}

