//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class SwitchTile : BaseTile
	{
	    public int number { get; set; }


        public override string icon {
            get
            {
                if (isOccupied)
                {
                    return "{00}";
                }
                else
                {
                    if (isUp)
                    {
                        return "{" + number + "^}";
                    }
                    return "{" + number + "v}";
                }
            }
        }

        public SwitchTile(int number)
        {
            this.number = number;
        }

	}
}

