//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class SwitchTile : BaseTile
	{
	    public int number;


        public override string icon {
            get
            {
                if (isUp)
                {
                    return "[" + number +"^]";
                }
                else
                {
                    return "[" + number +"v]";
                }
            }
        }

        public SwitchTile(int number)
        {
            this.number = number;
        }

	}
}

